### PR TITLE
Add new Create buttons. Closes #124

### LINKED ISSUE #124: Add to profile/Save as draft Buttons
The Figma files can be found [here](https://www.figma.com/file/K3LWtNFIgEryrldIbAqIVU/%CE%B2-add-content-buttons?node-id=0%3A1).

The "Add to profile"/"Save as draft" buttons should meet the following criteria:

- [x] On the add-content screen.
- [x] The cancel action is no longer a button but a link with standard link behavior except the underline is libscie-red.
- [x] "Cancel" returns the user to the last place they where before adding content.
- [ ] "Add to profile" takes you to the Profile feed
- [ ] "Save as draft" takes you to the Drafts feed

### PR DESCRIPTION
**Pull request by juliangruber**
image

### CODE REVIEW

**Comment by juliangruber** [comment]
> Is the splitting of adding main and supporting files on the add content screen now being done separately btw?

I'm not aware of this work item tbh

**Comment by jameslibscie** [comment]
> > Is the splitting of adding main and supporting files on the add content screen now being done separately btw?
> 
> I'm not aware of this work item tbh

The current situation is that the add content screen can now have a greyed out "Add to profile" button without there being an explanation of why. @psobrakseaton wanted to split up the adding of main files and supporting files into 2 different lists with 2 different `+` buttons to help with this.

I see 2 ways to proceed with this:
1. I write up updated copy for the `Upload files` section and we leave the main file selection as-is
2. We split up the add files into sections for main and supporting files as proposed by @psobrakseaton 

I believe @psobrakseaton is the owner for this. Do you have a preference? I personally think option 1 is fastest. I could provide new copy for "Upload files" today.

**Comment by juliangruber** [comment]
> @psobrakseaton wanted to split up the adding of main files and supporting files into 2 different lists with 2 different `+` buttons to help with this.

I am aware of the plan and have seen the designs, but it isn't on my list of work items so I wasn't aware of when we wanted to do this..Since I'm also not finishing some other tasks (likely), updating the copy would be best for me.

@psobrakseaton what do you think?

**Comment by juliangruber** [comment]
Also, how did this get missed? @psobrakseaton

**Comment by jameslibscie** [comment]
Cool, here's the copy:

*Add files*
These files are copied to a Hypergraph folder on your computer. If you want to work on them further, you can choose to work using Hypergraph's copies or reimport the files when you're done.

*Main file*
Required for adding to profile and sharing

**Comment by jameslibscie** [comment]
> Also, how did this get overlooked? @psobrakseaton @jameslibscie

Let's talk about this in tomorrow's process review :)

**Comment by jameslibscie** [comment]
Alignment looks good! Let me know when the copy is implemented and I'll approve

**Comment by juliangruber** [comment]
image

This looks off. Let's merge this as is and create a new issue for updating the description, that will be accompanied by designs.

**Comment by juliangruber** [comment]
I'm going to merge this now since I need changes from this branch in another

**Pull request merged**
