### PR TITLE
Fix color issue (Closes #328)

### LINKED ISSUE #328: Navigation menu text changes color unexpectedly
## Description

The navigation menu text changes color while using Hypergraph.

## To Reproduce

1. Build from main
2. Go to profile
3. Click edit profile

## Expected behavior

Navigation menu text stays white.

## Actual behavior

Navigation menu text changes color (grey, red, green).

## Screenshots

Screen Recording 2020-11-16 at 09 18 56 2020-11-16 09_21_27

## System

- OS (incl. version): macOS 10.15.7
- Hypergraph Desktop version: [`main@a34153ec0d137a79a42ad572437eecd64191c254`](https://github.com/hypergraph-xyz/desktop/commit/a34153ec0d137a79a42ad572437eecd64191c254)

## Additional context

This issue did not exist in the 0.8.0 release.

### PR DESCRIPTION
**Pull request by chartgerink**
For some odd reason the removal of `prettier-standard` caused the issue in #328. I'm not sure I understand *why* so any feedback people might have, is much appreciated.

Nonetheless, closes #328.

### CODE REVIEW

**Comment by juliangruber** [comment]
There must have been a change in syntax when you fixed it, and not just reformatting. I suggest to closely look at the code, and also inspect the DOM tree to see where the coloring is coming from.

**Comment by chartgerink** [comment]
> 
> 
> There must have been a change in syntax when you fixed it, and not just reformatting. I suggest to closely look at the code, and also inspect the DOM tree to see where the coloring is coming from.

Thanks! I could've inspected the DOM more closely.

I tried isolating the issue, and the interesting part was that reintroducing the `prettier-standard` formatting for all `app/` files that changed actually didn't fix the issue. If I left them all at the new formatting, but changed `package-lock.json` and `package.json`, it did fix it.

For now I opened #332 for this to stay on the radar ☺️

**Comment by juliangruber** [comment]
> the interesting part was that reintroducing the `prettier-standard` formatting for all `app/` files that changed actually didn't fix the issue

This is to be expected, as the tool should not change the syntax, just the formatting. Formatting can not cause this issue.

**Comment by juliangruber** [comment]
I can confirm there are rendering differences depending on the version of `standard`. This is terrible :cold_sweat:

**Pull request merged**
