### PR TITLE
Draft for new content types

### PR DESCRIPTION
**Pull request by jameslibscie**
Draft PR that implements in-progress wikidata-identifier update: https://github.com/hypergraph-xyz/wikidata-identifiers/pull/4
and content type design from https://www.figma.com/file/zTtZEFkwoZnMZjUJiC8VpH/%23166---Add-author(s)

image

### CODE REVIEW

**Review by juliangruber — APPROVED** [review]

**Review by chartgerink — COMMENTED** [review]
It's according to the design so 👍 on that!

It raises a bit the question of whether we want the "Follows from" and "Content type" to be the same? I see in the designs "Follows from" isn't included and I get a visual inconsistency now (arrow bigger, height 32px v 40px, font size difference). I would appreciate @psobrakseaton's ideas on this.

Screenshot 2020-08-26 at 13 24 12

Does anybody else feel this is the limit for a dropdown menu?

**Review by juliangruber — CHANGES_REQUESTED** [review]
image

The now longest content type breaks the current design

**Comment by juliangruber** [comment]
> Does anybody else feel this is the limit for a dropdown menu?

To me this looks wrong too

**Comment by psobrakseaton** [comment]
I 100% agree. The dropdown needs to be changed out for something else. I think something like a tag cloud or the like could potentially be a good, space saving solution here.

**Review by juliangruber — APPROVED** [review]

**Pull request merged**
