### PR TITLE
Add profile screen. Closes #14

### LINKED ISSUE #14: View profile
**User story**
As a Hypergraph user
I want to view my profile
so that I can get an overview of my published work

**Workflow**
- [x] Design
- [ ] Clickthrough
- [ ] Code
- [ ] Test

**Acceptance criteria**
- The profile page has a placeholder for an avatar in hex-shape
- The profile page displays the name and description (if a description exists - right now there is no way to do so from Desktop)
- If there are no published content modules, the profile page displays a message (in place of the "That's all of [profile name]'s content" and using the same style): "No content yet... 🤔"
- The profile page displays a list of published content modules

**Design**

Screenshot 2020-02-27 at 09 53 23

**edit** by @juliangruber: add design

### PR DESCRIPTION
**Pull request by juliangruber**
Closes #14.

## TODO

- [x] scrolling behavior
- [x] connect to SDK

### CODE REVIEW

**Comment by jameslibscie** [comment]
Very nice @juliangruber!

I've noticed a few small things:
- My description doesn't show up
- Dev tools open by default when starting the software (if this is very practical for you, then that's fine for now)
- The 'Edit profile' and 'Add content +' buttons are missing a purple `border-bottom`
- I think the buttons and links should give a `cursor: pointer` 
- I get the feeling that the font weight and spacing is sometimes different than the clickthrough. For the profile name, buttons and "Content" heading it seems right, but everything else seems slightly more heavy and closer together than the designs. Is that correct and if so, is it possible to tweak it?
- The purple > arrow left of the "Content" heading is missing. Is this intentional?
- And of course the encoding thing. Are the .js files (or whatever contains the text) perhaps saved using non-UTF-8 encoding?

This might seem like a lot, but it's all small stuff :) Great work!

**Comment by juliangruber** [comment]
> * The purple > arrow left of the "Content" heading is missing. Is this intentional?

If you check the latest designs this has been removed

**Comment by juliangruber** [comment]
> * I get the feeling that the font weight and spacing is sometimes different than the clickthrough. For the profile name, buttons and "Content" heading it seems right, but everything else seems slightly more heavy and closer together than the designs. Is that correct and if so, is it possible to tweak it?

I turned on font smoothing to make the text slightly lighter. In terms of condensing, Patch confirmed that all text should have a letter spacing of 0.05em, which isn't consistently implemented in the designs, hence the difference.

**Comment by juliangruber** [comment]
> This might seem like a lot, but it's all small stuff :)

Thank you for reporting every single one!

**Comment by juliangruber** [comment]
> * The 'Edit profile' and 'Add content +' buttons are missing a purple `border-bottom`

FYI it's more useful to me to report what's wrong instead of suggesting implementations. Here there was no border bottom missing, but the line height was wrong. This just adds a bit of confusion

**Comment by jameslibscie** [comment]
> > * The 'Edit profile' and 'Add content +' buttons are missing a purple `border-bottom`
> 
> FYI it's more useful to me to report what's wrong instead of suggesting implementations. Here there was no border bottom missing, but the line height was wrong. This just adds a bit of confusion

I should really stop trying to be smart all the time 😅

**Comment by juliangruber** [comment]
> Very nice @juliangruber!
> 
> I've noticed a few small things:

All are addressed. Please use GitHub's pull request review feature next time, then I can simply request another review when everything has been fixed 🙏

**Comment by juliangruber** [comment]
> If it's 3 lines, it looks slightly off-centre vertically.
> 
> Also, I'm wondering whether the description should start in a fixed place or always be vertically centred. This might look better for 1- or 2-line descriptions, but I'll leave that up to @psobrakseaton to decide.

I don't think this is too bad, in our designs everything is aligned top left, and in my opinion this is a micro optimization. I prefer it this way, but of course it's for Patch to decide

**Comment by juliangruber** [comment]
If you center this vertically, there will also be some cases where it doesn't align well

**Comment by psobrakseaton** [comment]
Ill review it this weekend and get back to you.

**Comment by juliangruber** [comment]
> * I think the buttons and links should give a `cursor: pointer`

I've removed this again as at least on mac a button doesn't usually have a pointer, it only has it in websites.

**Comment by juliangruber** [comment]
I'm going to continue work right in #master now as I need to work on many features at the same time, for the product demo

**Pull request merged**
