### PR TITLE
Add greyed out version of content button

### PR DESCRIPTION
**Pull request by chartgerink**
This PR changes the add content button to the [mono500 color](https://github.com/libscie/design-library) when it is already showing.

## Active

image

## Inactive

image

### CODE REVIEW

**Comment by psobrakseaton** [comment]
Pretty good! How much extra work would it be to remove the hover effect (no highlight) and to change the cursor to the disabled state the same as the add to profile/save as draft buttons on the form?

**Comment by chartgerink** [comment]
I could create a quick implementation rather easily. Shall I go ahead and do that?

**Comment by chartgerink** [comment]
@psobrakseaton I made the changes as requested. Would you be so kind to review? I can't screencap the cursor on Windows.

**Review by psobrakseaton — APPROVED** [review]
This is perfect! Thanks Chris! How do I do gifs on here? Please imagine a :cheering: gif...

**Comment by chartgerink** [comment]
Thanks! 

Best is to find a GIF you like and use the image embed in markdown - `alt text`

**Pull request merged**
