### PR TITLE
Add Author(s). Closes #166

### LINKED ISSUE #166: Add author(s)
On the edit content screen, add the ability to add and remove authors from content.

- [x] add dropdown of all locally known profiles
- [x] add button to add author
- [x] display all currently added authors
- [x] for each, let author be removed

[Figma](https://www.figma.com/file/zTtZEFkwoZnMZjUJiC8VpH/%23166---Add-author(s))

### PR DESCRIPTION
**Pull request by juliangruber**
This lets you add and remove authors when creating and editing content.

Closes #166

## Todo

- [x] Multiple draft authors

image

I see two options:
     - Also turn draft authors into links (preferred), and use another indicator for whether this author has added the content to their profile
    - Add commas, between, authors

- [ ] Spacing in edit form

image

Since we haven't implemented the main / supporting files split in the edit form, the spacing is different than in figma

### CODE REVIEW

**Comment by juliangruber** [comment]
Design update:

image

image

image

image

**Review by jameslibscie — APPROVED** [review]

**Review by jameslibscie — CHANGES_REQUESTED** [review]
When deleting multiple-author content that is registered to the main author, it also seems to try to deregister it from the 2nd author's profile, but that profile is not writable.

**Comment by juliangruber** [comment]
> When deleting multiple-author content that is registered to the main author, it also seems to try to deregister it from the 2nd author's profile, but that profile is not writable.

This should be an SDK bug, all Hypergraph does is `p2p.delete` on the content module.

**Comment by juliangruber** [comment]
Bug reports:
https://github.com/hypergraph-xyz/desktop/issues/251
https://github.com/p2pcommons/sdk-js/issues/232

**Review by jameslibscie — APPROVED** [review]

**Review by chartgerink — APPROVED** [review]

**Review by psobrakseaton — APPROVED** [review]

**Pull request merged**
