### PR TITLE
Add/hover plus

### PR DESCRIPTION
**Pull request by chartgerink**
One of the walkthroughs mentioned that the inconsistency between the hover plus and the omnipresent add content button was bugging them. I talked with @psobrakseaton and he mentioned it was just legacy and indeed inconsistent.

I made an adjustment to have them be similar in style. I had to shrink it down a tad, because the original plus was 48x48px, and the omnipresent is 56x64px, which led to an overflow in the hover box.

# Screenshot of implementation

Screenshot 2020-09-24 at 11 57 24

## Overflow issue mentioned (not implemented)

Screenshot 2020-09-24 at 11 40 33

### CODE REVIEW

**Comment by juliangruber** [comment]
Are there designs for how this is supposed to look?

**Comment by juliangruber** [comment]
I'm not sure what the PR description means. Are you satisfied with how it is?

**Review by juliangruber — APPROVED** [review]
LGTM! Nice change

**Comment by chartgerink** [comment]
> Are there designs for how this is supposed to look?

This was more emergent than designed. Coordinated with @psobrakseaton and he approved too :) 

> I'm not sure what the PR description means. Are you satisfied with how it is?

I like it better with the hex 😊

**Comment by juliangruber** [comment]
Ok yeah makes sense to me too 👏

**Pull request merged**
