### PR TITLE
add create content with parent module. #44

### PR DESCRIPTION
**Pull request by juliangruber**
This adds the first part of parent modules: creating a module with a parent, and displaying that parent in the content details screens.

I'm going to base all further parent module pull requests on this one, as they both rely on above mentioned changes.

## Screens

1. Add + (only visible when mouse over)

Screenshot 2020-03-23 at 17 14 09

2. Create content with parent

Screenshot 2020-03-23 at 17 10 38

3. View content with parent

Screenshot 2020-03-23 at 17 10 44

### CODE REVIEW

**Comment by psobrakseaton** [comment]
So far I think this is a great solution to the parent module/following-from issue. Can the "open folder" and "export .zip" buttons be moved into the header bar? 

Second, if there is "no parent" can that part of the form disappear completely?

**Comment by juliangruber** [comment]
> Can the "open folder" and "export .zip" buttons be moved into the header bar?

This is independent of this issue, please constrict your review to the changes here. Can you send designs for this, or explain in words how this should look?

> Second, if there is "no parent" can that part of the form disappear completely?

It already only shows when there is a parent:

Screenshot 2020-03-23 at 17 38 54

**Comment by chartgerink** [comment]
For a first implementation w/o designs from @psobrakseaton, it's looking really good :) We'll definitely need to design it out a bit more to clarify some of the concepts.

My only suggestion is to not allow parenting when the content module is unpublished (i.e., no `+` gets displayed then). This is not in the spec per se, but it seems to make sense in my head right now to disallow this from a UX perspective? It's like continuing on unpublished work, it makes it possible that the retracing of steps at a later timepoint gets complicated due to availability issues.

**Comment by juliangruber** [comment]
> My only suggestion is to not allow parenting when the content module is unpublished (i.e., no `+` gets displayed then).

This is unintuitive to me, as you're writing your paper I'd expect to create following content without publishing prior steps first. Please correct me if I'm wrong, but isn't basing drafts on drafts important, especially in uncertain areas?

**Comment by juliangruber** [comment]
> For a first implementation w/o designs from @psobrakseaton, it's looking really good :) We'll definitely need to design it out a bit more to clarify some of the concepts.

Thanks! I didn't want to make any design decisions, so I implemented the simplest possible visual changes.

**Comment by chartgerink** [comment]
I'd need to think about this a bit more in-depth and about the second/third order effects and how they relate to the higher levels of the vision. For now, we can park it (not a huge thing here) and I'll come back to it later through the specs.

**Comment by psobrakseaton** [comment]
I currently don't have an opinion regarding the not showing of a + when there is unpublished content, but I will give it some thought.

As for the implementation of the + icon, I would like to suggest the following, it's purely a visual redesign:

-Upon hover, a 128px bar slides in from the right further reinforcing that you are adding to this module.

-Make that whole area clickable for the sake of accessibility.

 [Here's the Figma board]([](https://www.figma.com/file/5aQDo21KHshfXedOwI3z0o/desktop-follows-from?node-id=61%3A5))

**Comment by psobrakseaton** [comment]
Also, I forgot to say I quickly experimented with moving the bookmark function to the side as well. No need to implement that now.

**Comment by juliangruber** [comment]
> I'd need to think about this a bit more in-depth and about the second/third order effects and how they relate to the higher levels of the vision. For now, we can park it (not a huge thing here) and I'll come back to it later through the specs.

Sounds great! :) If you feel strongly about this, I can also disable the `+` for unpublished content, it's an easy change.

**Comment by juliangruber** [comment]
Merging, as approved by Patch in Slack

**Comment by jameslibscie** [comment]
@juliangruber @chartgerink The CLI currently only allows selecting a published content module afaik, but the specs don't say anything about this. I'll create a specs issue to think about this and then make the products consistent.

**Pull request merged**
