### PR TITLE
Renamed (un)publish buttons to add to/remove from profile

### LINKED ISSUE #66: Change "publish" and "unpublish" to "add to / remove from profile"
As per the terminology decision meeting of 2020/04/14

**Acceptance criteria**
- [ ] Update "Publish" button to "Add to profile"
- [ ] Update "Unpublish" button to "Remove from profile"

*Note:* the welcome modal text does NOT need to be updated yet

### PR DESCRIPTION
**Pull request by jameslibscie**
I had a look around and (un)publish terminology is still used in the following places
- SDK method
- `[Un]PublishedAuthor` component
- `[set]IsPublished` state
- `Hex[Un]Published` component

Do you agree @juliangruber that it's best to leave this naming in place for now, until the terminology settles? Would it be wise to create an issue as a reminder to bring this in line later on?

Closes #66

### CODE REVIEW

**Comment by jameslibscie** [comment]
@juliangruber I've tried to fix the conflict by doing this:
- checkout master
- pull
- checkout branch
- merge master
- accepting incoming change
- making my changes again (because they were super easy)
- add .
- commit -a
- push

Is that correct procedure and is the result correct? Fixing the conflict in the web editor looked like a nightmare.

**Comment by juliangruber** [comment]
> * making my changes again (because they were super easy)

did you instead of resolving the conflicts just accept the incoming changes because yours were easy to replay? otherwise usually you would try to resolve the conflict line by line. if you want we can screenshare doing this next time

**Comment by juliangruber** [comment]
> Do you agree @juliangruber that it's best to leave this naming in place for now, until the terminology settles? Would it be wise to create an issue as a reminder to bring this in line later on?

Hmm to me consistency inside a project is really important, more so than across projects. So we can't do anything about the SDK methods right now for example, but could rename these other components.

What about

- `[Un]PublishedAuthor` -> `AuthorWith[out]ModuleOnProfile`
- `[set]IsPublished` -> `[set]IsOnProfile`
- `Hex[Un]Published` -> `Hex[Not]OnProfile`

**Comment by jameslibscie** [comment]
@juliangruber In this case, yes. In a more complicated situation I'd love for some help with line by line resolving. Have resolved conflicts before using other technologies, but I think not knowing the code makes it more complicated now as well.

**Comment by jameslibscie** [comment]
I made it like this, but actually now I'm not sure this is the best approach:
* `[Un]PublishedAuthor` -> `AuthorOf[ProfileContent/Draft]`
* `[set]IsPublished` -> `[set]IsOnProfile`
* `Hex[Un]Published` -> `HexIndicatorIs[OnProfile/Draft]`

I think using the terminology "profile content" vs "draft" will be helpful and I can add this to the glossary if you agree. We could actually use this for all 3 then:

* `[Un]PublishedAuthor` -> `AuthorOf[ProfileContent/Draft]`
* `[set]IsPublished` -> `[set]IsProfileContent`
* `Hex[Un]Published` -> `HexIndicatorIs[ProfileContent/Draft]`

I added "Indicator" because I think it adds clarity.

**Pull request merged**
